# Generated by Django 3.0.5 on 2021-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.DecimalField(decimal_places=0, max_digits=20)),
                ('title', models.CharField(max_length=200)),
                ('cexPhotoUrl', models.CharField(max_length=200)),
                ('booktopiaPhotoUrl', models.CharField(max_length=200)),
                ('cexSell', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cexBuy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cexTrade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
